version: '3.4'

services:
  provisioner:
    build:
      context: .
      dockerfile: ./files/dockerFiles/DockerfileControlNode
    stdin_open: true
    tty: true
    
networks: 
  default: 
    external: 
      name: ansibleTestNetwork