name: CI
on:
  push:
    branches: [ main ]

jobs:
  Compile-Nginx-And-Create-Deb-Package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test1
        run: |
          cd files/nginx/
          bash compile.sh
      - name: Upload .deb package artifact
        uses: actions/upload-artifact@v2
        with:
          name: nginx-personal-compilation
          path: files/nginx/nginx-personal-compilation_1.0-1.deb
