name: CI
on:
  push:
    branches: [ main ]

jobs:
  Compile-Nginx-And-Create-Deb-Package:
    runs-on: ubuntu-latest
    steps:
      - name: Test1
        run: |
          pwd
      - name: Test2
        run: |
          ls -ltrahR
